version: '3.3'

services:
  rosmaster:
    build:
      dockerfile: Dockerfile
      context: .
    image: leonardoedgar/sauvc-master:latest
    container_name: rosmaster
    network_mode: "host"
    privileged: true
    environment:
      - DISPLAY=unix$DISPLAY
      - MACHINE=${MACHINE}
    shm_size: 256M
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - ./catkin_ws/src/sauvc:/home/leonardo/catkin_ws/src/sauvc
      - ./catkin_ws/src/rosserial:/home/leonardo/catkin_ws/src/rosserial
      - ~/Arduino/libraries:/home/leonardo/Arduino/libraries
      - ./build_arduino_lib.sh:/home/leonardo/Arduino/libraries/build_arduino_lib.sh
    stop_signal: SIGINT
    working_dir: /home/leonardo
    command: sleep infinity
